#ifndef FACTORY_PRODUCTION_LINE_SIMULATION_PRODUCTIONLINE_H
#define FACTORY_PRODUCTION_LINE_SIMULATION_PRODUCTIONLINE_H


class productionLine {
private:

};


#endif //FACTORY_PRODUCTION_LINE_SIMULATION_PRODUCTIONLINE_H
